### ISSUE TITLE
Only check for updates if the user requests to do so

### ISSUE THREAD

**Issue by probonopd** [antony-jr/QTalarm-AppImage#2]
Please only check for updates if the user requests to do so. Otherwise it is a forced "phone home" which can be used to track users who don't like to be tracked, which even may be illegal in some jurisdictions (google "GPDR").

**Comment by antony-jr** [comment]
So I have to attach an option to the menu bar ? But this is an Auto Update feature. Or Should we ask the user if we can send requests for checking updates ??? (only the first time)

**Comment by antony-jr** [comment]
Then how does Discord and other apps automatically checks for update on startup ?

**Comment by probonopd** [comment]
Yes please have it attach "Check for updates..." to the menu bar and only perform the check if the user selects that menu item.

Reference:
* https://github.com/antony-jr/AppImageUpdaterBridge/issues/7#issuecomment-438552283

**Comment by antony-jr** [comment]
Okay , I will work on it.

**Comment by antony-jr** [comment]
I'm just curious , But auto updaters like electron updater seems to just do the update without any warning , don't they violate GDPR ?

**Comment by probonopd** [comment]
I am not a lawyer but I think they are at least(!) in a legal grey zone.

**Comment by antony-jr** [comment]
Added ``` -n , --no-auto-update ``` argument to **updatedeployqt** , also ```-m , --qmenubar-name``` argument to specify the QObject name to make it straight forward. **Use the built in Auto Updater in QTalarm AppImage to see the updated version.**(now it attaches the updater initialization to **Check for Update** option in the menu bar)

**Note** : The best part is that there is no need to edit any of the source files of QTalarm. The source files are untouched.

![Screenshot_20190526_094457](https://user-images.githubusercontent.com/33930174/58377337-994b0600-7f9b-11e9-9a8a-acdf4e74abf9.png)

![Screenshot_20190526_095034](https://user-images.githubusercontent.com/33930174/58377353-de6f3800-7f9b-11e9-9daf-8611b7c1a083.png)

**Comment by probonopd** [comment]
This is great news. Is there a way to put the update check into the existing About menu?

**Comment by antony-jr** [comment]
> This is great news. Is there a way to put the update check into the existing About menu?

All QObject has a name which is by default not set. This name can be set by **QObject::setObjectName()** method. The name can be retrieved by **QObject::objectName()** method. Now if we know the object name of the about menu in question which should be given by the developer then it is possible to put it in the existing about menu. But without the object name , at best we can only create a new menu option. Most typically all **GUI Widgets** has a object name , but the developer has to mention it when deploying the updater.

**Comment by antony-jr** [comment]
We can also guess for the about menu , like if the QMenu object name is nearly similar to **'about'** then we can insert our option to that menu else just insert it to the QMenuBar object.

**Comment by probonopd** [comment]
Sounds like a plan :+1:

**Comment by probonopd** [comment]
This is what [Sparkle](https://sparkle-project.org/) does:

![](https://user-images.githubusercontent.com/2480569/32457121-351d4aac-c328-11e7-84ce-14f28c8941ac.png)

Note that checkbox above the buttons...

**Comment by antony-jr** [comment]
Interesting but remembering stuff requires to write configuration file for the user under .config directory. (Using QSettings). But This is exciting , Even **Sparkle can't enable their updater with zero code change.**

**Comment by antony-jr** [comment]
Okay , give me a day or two. I feel like implementing this. I also gonna furnish the tool and also make a good documentation for that.

**Comment by probonopd** [comment]
Why not have a QSetting for the updater itself rather than the app it updates?

**Comment by antony-jr** [comment]
> Why not have a QSetting for the updater itself rather than the app it updates? 

Because every application needs to be isolated. Like some application they want recent updates and some not. I'm not really sure about this but I think making it isolated has some advantages. Also it would be meaningless to have inbuilt updater. If we use a global settings then it would simply be a global updater with duplicate binary of itself inside all AppImages which uses this updater. With isolation each updater has unique behavior and habits. Like I want to skip the next update because it seems buggy and only that program and nothing else. Also If we do not isolate then the configuration file would be big glob of data on update information of all AppImages using this updater which takes longer time to read and parse, in worst case scenario takes a minute or two if you have like 100 AppImages which uses this updater which is not unlikely.

**Comment by antony-jr** [comment]
Also for github transport mechanism we can get the release notes but not sure of other kinds of transport.

**Comment by probonopd** [comment]
> Also for github transport mechanism we can get the release notes but not sure of other kinds of transport.

👍 That would be pretty awesome and would cover already >90% of cases, then we could use pretty much 1:1 the design from Sparkle for the dialog. For other hosting, we could potentially use the Sparkle [appcast format](https://sparkle-project.org/files/sparkletestcast.xml).

References:
* https://github.com/AppImage/AppImageUpdate/issues/34
* https://github.com/AppImage/AppImageUpdate/issues/83#issuecomment-375980952

**Comment by probonopd** [comment]
The latest build has "Check for Update" in the About menu, which is great :+1: 

But do we need this extra window at all?

![](https://user-images.githubusercontent.com/2480569/58903981-2efe3800-86f6-11e9-84e1-c50da91e24c4.png)

Also, if I may have a preference, let's not have an extra icon for it, this should feel as "minimal" and as "native" as possible.

**Comment by antony-jr** [comment]
I am kinda of in the middle of creating the final product , it was just a test , I still need to do a few more changes and you can see the end result soon. I think the window is needed since if you click on **check for update** option and nothing happens the user may think that nothing happens. But this is totally optional.

A configuration file(updatedeployqt.json) now decides the behavior of the updater , this repo also has one , head to https://github.com/TheFutureShell/updatedeployqt for more information. I still need to build a documentation of that tool. Here is how the config file should look like,

```
{
   "name" : "QTalarm AppImage", // Not needed , optional
   "version" : "v0.0.1", // Not needed , optional
   "qt-version" : "5.9.3",
   "bridge" : "AppImageUpdater",
   "manual-update-check" : {
	   "qmenu-name" : "menuAbout"
   }
}
```

**EDIT** : Now the command line is just , ```updatedeployqt AppDir```

**Comment by probonopd** [comment]
Thank you, I think we can close this ticket here then.
